export const TOKEN_URL_PATH = '/oauth/token'

export const MAX_HOURS_PER_CAMPAIGN_SCHEDULE = 1
export const MAX_WEEKLY_DAYS_PER_CAMPAIGN_SCHEDULE = 1
export const MAX_MONTHLY_DAYS_PER_CAMPAIGN_SCHEDULE = 4

export const DEFAULT_IDENTITY_RESOLUTION_ATTRIBUTE = 'name'
export const DEFAULT_HOURLY_SCHEDULE_DAY = ['9']
export const DEFAULT_WEEKLY_SCHEDULE_DAY = ['MON']
export const DEFAULT_MONTHLY_SCHEDULE_DAY = ['1']
export const DEFAULT_CAMPAIGN_DURATION = 'P2W'
export const DEFAULT_MAX_ENTITLEMENTS_PER_POLICY_SIDE = 400
export const DEFAULT_MAX_ACCESS_ITEMS_PER_CAMPAIGN = 10000
export const DEFAULT_MAX_CONCURRENT_POLICIES = 3
export const SEARCH_QUERY_BATCH_SIZE = 50
export const API_429_MAX_RETRIES = 15
export const API_5XX_MAX_RETRIES = 5
export const API_RETRY_BASE_DELAY_MS = 2000
export const API_RETRY_MAX_DELAY_MS = 60000
export const API_REQUEST_TIMEOUT_MS = 120000
export const KEEP_ALIVE_INTERVAL_MS = 60000
